### PR TITLE
Add regexp Matcher

### PR DESCRIPTION
**Pull request by bep**
I had a use for this in one of my projects, so thought it would be of use to others.

Note: 

* I'm not totally married to the name of the func here ...
* The panics are unfortunate, but I see no cleaner way here

### CODE REVIEW

**Comment by asdine** [comment]
The problem you faced here is a problem that will certainely happen as we add new Matchers. We should change the interface to allow Match to returns a bool plus an error:

```go
Match(interface{}) (bool, error)
```
What do you think?

**Comment by bep** [comment]
Makes sense, if you fix that I'll update this PR.

**Comment by bep** [comment]
However, that will not fix the potential panic here:

https://github.com/asdine/storm/pull/75/files#diff-a71acd5431547b2d7824ae1a68e4affaR21

But I guess that is unavoidable...

**Comment by asdine** [comment]
Done 74dc8827ef5a0441101ed2a2fccdcfc37b84893e
You are right for the `MustCompile` it is unavoidable

**Comment by bep** [comment]
PR updated.

**Comment by asdine** [comment]
Awesome, storing the error to return it later is a great idea, the regex cache too

**Comment by bep** [comment]
Yes, regexp are often faster than you believe -- but compiling them is slowish. That cache assumes a fairly static usage of the regexps, aka not building dynamic regexps from a busy web interface, but we can add a eviction policy or similar later.

**Pull request merged**
