### PR TITLE
Issue 53 Node.One() now returns ErrNotFound if bucket doesn't exist

### PR DESCRIPTION
**Pull request by bits01**

### CODE REVIEW

**Comment by asdine** [comment]
It would be nice to have the same behavior between `Find`, `One`, `All`, `AllByIndex`, `Range`, `Count`, etc.

**Comment by bits01** [comment]
Hmm, yes it would, I only ran into One() so far. Let me take a look at the rest.

**Comment by bits01** [comment]
More changes for the other cases, please review whether everything is covered. Thanks.

**Comment by asdine** [comment]
Great job! Thank you!

**Pull request merged**
