### PR TITLE
Add Sereal codec

### LINKED ISSUE #17: Add Sereal codec
See https://github.com/Sereal/Sereal

### PR DESCRIPTION
**Pull request by bep**
Fixes #17

### CODE REVIEW

**Comment by bep** [comment]
OK, this doesn't build on Go 1.3 it seems ... which is a pretty old Go version.

**Comment by asdine** [comment]
Can you update the .travis.yml and drop the v1.3 please? It is too old to keep maintaining it

**Comment by bep** [comment]
Will do.

**Comment by asdine** [comment]
Thank you!

**Pull request merged**
