### PR TITLE
v3: use semantic import versioning as required by go

### PR DESCRIPTION
**Pull request by chappjc**
Resolving https://github.com/asdine/storm/issues/255

Note that this will require a `v3.0.0` tag once merged to be usable by dependents.

### CODE REVIEW

**Comment by anjmao** [comment]
@asdine This PR looks correct, could we merge it?

**Comment by asdine** [comment]
Thank you! Sorry for the delay 🙏

**Comment by chappjc** [comment]
Np!  Thanks for merging.

I've updated my app to import "github.com/asdine/storm/v3" and all is well on my end, even without a v3.0.0 tag.

```
require github.com/asdine/storm/v3 v3.0.0-20191014164809-c6fa66c747fe
```

via `go get -u -v github.com/asdine/storm/v3`.

**Comment by chappjc** [comment]
BTW, if the `go` is still complaining about the invalid v2.2.0+incompatible version even if v3 is being used, you can prevent go from attempting to verify if (and failing) with a replace.

```
replace github.com/asdine/storm => github.com/asdine/storm v2.1.2+incompatible
```

I'm not sure if v2.2.0 will continue to cause issues for all consumers (`github.com/asdine/storm@v2.2.0+incompatible: invalid version: +incompatible suffix not allowed: module contains a go.mod file, so semantic import versioning is required`).  If it does, it may be necessary to entirely deprecate the tag by making a new tag `v2.2.0+deprecated`.

**Pull request merged**
